version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 4000:5000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
        #- /dev/video0:/dev/video0
    volumes:
      - /home/octoprint/ender_3_pro:/home/octoprint
